Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Page taht shows all blogs.
    path('blogs/', views.blogs, name='blogs'),
    # Detail page for a single blog
    path('blogs/<int:blog_id>/', views.blog, name='blog' )
    # Page for adding a new blog
    path('new_post/', views.new_post, name='new_post'),
    # Page for editing an entry.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

blogs/models.py
from django.db import models

class BlogPost(models.Model):
    """A post about blog."""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.title.upper()}  ...  {self.text}"

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'text': ''}

blogs/views.py
from django.shortcuts import render, redirect

from .models import BlogPost
from .forms import BlogForm

def index(request):
    """The home page for blogs."""
    return render(request, 'blogs/index.html')

def blogs(request):
    """Show all blogs."""
    blogs = BlogPost.objects.order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """Show a single blog and its entries."""
    blog = BlogPost.objects.get(id=blog_id)
    entries = blog.entry_set.order_by('-date_added')
    context = {'blog': blog, 'entries': entries}
    return render(request, 'blogs/blog.html', context)

def new_post(request):
    """Add a new post."""
    if request.method != 'POST':
        # No data submitted: create a blank form.
        form = BlogForm()
    else:
        # POST data submitted: process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

def edit_post(request, post_id):
    """Edit an existing post."""
    post = BlogPost.objects.get(id=post_id)
    blog = post.blogs

    if request.method != 'POST':
        # Initial request: pre-fill form with the current entry.
        form = BlogForm(instance=post)
    else:
        # POST data submitted; process data.
        form = BlogForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs', post_id=post.id)

    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

blogs/templates/blogs/base.html
<p>
  <a href="{% url 'blogs:index' %}">Blog Post</a> - 
  <a href="{% url 'blogs:blogs' %}">Blogs</a>
</p>

{% block content %}{% endblock content %}

blogs/templates/blogs/blog.html
{% extends 'blogs\base.html' %}

{% block content %}

  <p>Blog: {{ blog }}</p>

  <p>Entries:</p>
  <ul>
    {% for entry in entries %}
      <li>
        <p>{{ entry.date_added|date:'M d, Y H:i'}}</p>
        <p>{{ entry.text|linebreaks }}</p>
      </li>
    {% empty %}
      <li>There are no entries for this blog yet.</li>
    {% endfor %}
      </ul>

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}

{% block content %}

  <p>Blogs</p>

  <ul>
    {% for blog in blogs %}
      <li>{{ blog }}</li>
    {% empty %}
      <li>No blogs have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'blogs:new_post' %}">Add a new blog</a>
  <a href="{% url 'blogs:edit_post' blogs.id %}">Edit Post</a>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p><a href="{% url 'blogs:blogs' blogs.id %}">{{ blog }}</a></p>

  <p>Edit post</p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
<p>Blogs</p>

<p>Blogs can help people to find useful info in their daily life.</p>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>Add a new post:</p>

  <form action="{% url 'blogs:new_post' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add post</button>
  </form>

{% endblock content %}